In [1]:
import pickle
from src.cleaning import preparingDataset
from src.submission import prepareSubmission
import pandas as pd

In [34]:
# load the model from disk
loaded_model = pickle.load(open('./models/randomforest.sav', 'rb'))

In [35]:
loaded_model

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [36]:
test=preparingDataset('test.csv')

In [37]:
test.head()

,id,carat,depth,table,cut_Fair,cut_Good,cut_Ideal,cut_Premium,cut_Very Good,color_D,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,0,0.56,62.1,54.0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,1,0,0
1,1,1.05,61.9,56.0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,2,0.50,61.5,56.0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
3,3,0.80,62.8,56.0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,4,0.54,61.4,57.0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [28]:
X=test[['carat', 'depth', 'table', 'cut_Fair', 'cut_Good', 'cut_Ideal',
       'cut_Premium', 'cut_Very Good', 'color_D', 'color_E', 'color_F',
       'color_G', 'color_H', 'color_I', 'color_J', 'clarity_I1', 'clarity_IF',
       'clarity_SI1', 'clarity_SI2', 'clarity_VS1', 'clarity_VS2',
       'clarity_VVS1', 'clarity_VVS2']]

In [29]:
test['price']=loaded_model.predict(X)

In [30]:
test=test[['id','price']]

In [21]:
test.head()

          id         price
0          0   1451.753449
1          1   6685.845876
2          2   2037.005754
3          3   4938.159561
4          4   2416.535951
5          5  13587.931040
6          6    849.870583
7          7    772.350005
8          8    124.329849
9          9  13503.103659
10        10  -1570.931795
11        11   1023.248567
12        12   1885.468563
13        13   2026.987488
14        14   1950.459000
15        15   4208.140896
16        16   1265.350590
17        17   1737.112053
18        18   3685.470366
19        19   2198.857727
20        20   6095.299547
21        21   7709.852057
22        22   3708.311845
23        23  14430.222431
24        24    310.123326
25        25   5898.223685
26        26   1898.857409
27        27  10401.536464
28        28    256.691886
29        29    525.597923
...      ...           ...
13455  13455   3145.423865
13456  13456   -322.464363
13457  13457  20936.599770
13458  13458   7711.816894
13459  13459   1207.529781
13460  13460   7492.788815
13461  13461   5826.338762
13462  13462   2818.515744
13463  13463   6710.972094
13464  13464     31.839698
13465  13465   5530.725288
13466  13466   1218.232784
13467  13467   2580.439782
13468  13468   2086.551369
13469  13469   -755.752893
13470  13470  11425.087638
13471  13471  12208.794396
13472  13472   -506.781553
13473  13473   2216.796015
13474  13474   2721.134219
13475  13475    -42.056242
13476  13476   1274.697882
13477  13477   -874.311980
13478  13478    806.301327
13479  13479   2477.782031
13480  13480   2340.124967
13481  13481   3044.051473
13482  13482  10443.365052
13483  13483  -1640.489717
13484  13484   2138.195827

[13485 rows x 2 columns]